import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0F0F0F',
  },
  scrollView: {
    flex: 1,
  },
  content: {
    paddingHorizontal: 24,
    paddingTop: 16,
    paddingBottom: 40,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 32,
  },
  backButton: {
    padding: 8,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  placeholder: {
    width: 40,
  },
  descriptionContainer: {
    alignItems: 'center',
    marginBottom: 32,
    paddingVertical: 24,
    paddingHorizontal: 16,
    backgroundColor: '#1A1A1A',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#333333',
  },
  descriptionTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginTop: 16,
    marginBottom: 8,
  },
  descriptionText: {
    fontSize: 14,
    color: '#A0A0A0',
    textAlign: 'center',
    lineHeight: 20,
  },
  refreshFromContractButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#1A1A1A',
    paddingVertical: 12,
    paddingHorizontal: 18,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#8B5CF6',
    gap: 6,
    alignSelf: 'center',
    minWidth: 160,
  },
  refreshFromContractText: {
    color: '#8B5CF6',
    fontSize: 12,
    fontWeight: '500',
    textAlign: 'center',
  },
  refreshButtonDisabled: {
    opacity: 0.6,
  },
  section: {
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 12,
  },
  deviceCard: {
    backgroundColor: '#1A1A1A',
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#333333',
  },
  deviceHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
    gap: 12,
  },
  deviceName: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#FFFFFF',
    flex: 1,
  },
  editNameText: {
    color: '#8B5CF6',
    fontSize: 12,
    fontWeight: '600',
  },
  statusBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  statusConnected: {
    backgroundColor: '#10B981',
  },
  statusDisconnected: {
    backgroundColor: '#EF4444',
  },
  statusText: {
    fontSize: 12,
    fontWeight: '600',
  },
  statusTextConnected: {
    color: '#FFFFFF',
  },
  statusTextDisconnected: {
    color: '#FFFFFF',
  },
  deviceDetails: {
    gap: 8,
  },
  editIconButton: {
    padding: 6,
  },
  editNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 8,
  },
  nameInput: {
    flex: 1,
    backgroundColor: '#0F0F0F',
    borderWidth: 1,
    borderColor: '#333333',
    color: '#FFFFFF',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  saveNameButton: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    backgroundColor: '#10B981',
    borderRadius: 8,
  },
  saveNameButtonText: {
    color: '#FFFFFF',
    fontWeight: '700',
  },
  cancelEditButton: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    backgroundColor: '#1F1F1F',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#333333',
  },
  cancelEditButtonText: {
    color: '#FFFFFF',
    fontWeight: '600',
  },
  toastContainer: {
    position: 'absolute',
    left: 24,
    right: 24,
    bottom: 32,
    backgroundColor: '#8B5CF6',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 16,
    shadowColor: '#000',
    shadowOpacity: 0.25,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 5,
    marginBottom: 13
  },
  toastText: {
    color: '#FFFFFF',
    fontSize: 14,
    textAlign: 'center',
    fontWeight: '600',
  },
  toastSuccess: {
    backgroundColor: '#10B981',
  },
  toastSuccess: {
    backgroundColor: '#10B981',
  },
  overlayCenter: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.6)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  confirmModal: {
    width: '100%',
    backgroundColor: '#111111',
    borderRadius: 16,
    padding: 20,
    borderWidth: 1,
    borderColor: '#2D2D2D',
    // borderColor: '#8B5CF6',3 
  },
  confirmHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 12,
  },
  confirmTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  confirmMessage: {
    fontSize: 14,
    color: '#CCCCCC',
    lineHeight: 20,
    marginBottom: 16,
  },
  confirmActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 10,
  },
  confirmCancelButton: {
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 10,
    backgroundColor: '#1F1F1F',
    borderWidth: 1,
    borderColor: '#2D2D2D',
  },
  confirmCancelText: {
    color: '#FFFFFF',
    fontWeight: '600',
  },
  confirmConfirmButton: {
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 10,
    borderWidth: 1,
  },
  confirmConfirmText: {
    fontWeight: '700',
  },
  detailRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  detailLabel: {
    fontSize: 14,
    color: '#A0A0A0',
    fontWeight: '500',
  },
  detailValue: {
    fontSize: 14,
    color: '#FFFFFF',
    fontWeight: '500',
  },
  detailValueFull: {
    fontSize: 12,
    color: '#FFFFFF',
    fontWeight: '500',
    fontFamily: 'monospace',
    flex: 1,
    flexWrap: 'wrap',
  },
  keyTypeBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  sudoBadge: {
    backgroundColor: '#EF4444',
  },
  restrictedBadge: {
    backgroundColor: '#10B981',
  },
  keyTypeText: {
    fontSize: 12,
    fontWeight: '600',
  },
  sudoText: {
    color: '#FFFFFF',
  },
  restrictedText: {
    color: '#FFFFFF',
  },
  disconnectButton: {
    padding: 8,
    backgroundColor: '#2A1A1A',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#EF4444',
  },
  emptyState: {
    alignItems: 'center',
    paddingVertical: 40,
    paddingHorizontal: 20,
  },
  emptyStateText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#666666',
    marginTop: 16,
    marginBottom: 8,
  },
  emptyStateSubtext: {
    fontSize: 14,
    color: '#666666',
    textAlign: 'center',
  },
  loadingContainer: {
    alignItems: 'center',
    paddingVertical: 40,
  },
  loadingText: {
    fontSize: 16,
    color: '#A0A0A0',
  },
  createButton: {
    backgroundColor: '#8B5CF6',
    borderRadius: 12,
    paddingVertical: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    marginBottom: 24,
  },
  createButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  securityNotice: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: '#1A0A2E',
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: '#8B5CF6',
    gap: 12,
  },
  securityNoticeText: {
    flex: 1,
    fontSize: 14,
    color: '#A0A0A0',
    lineHeight: 20,
  },
  deviceActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginTop: 16,
  },
  detailsButton: {
    padding: 8,
    backgroundColor: '#1A0F2E',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#8B5CF6',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalContainer: {
    backgroundColor: '#1A1A1A',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#333333',
    width: '100%',
    maxWidth: 400,
    maxHeight: '80%',
    shadowColor: '#000000',
    shadowOffset: {
      width: 0,
      height: 10,
    },
    shadowOpacity: 0.5,
    shadowRadius: 20,
    elevation: 10,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#333333',
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#FFFFFF',
    letterSpacing: 0.3,
  },
  closeButton: {
    padding: 4,
  },
  modalContent: {
    padding: 20,
  },
  deviceInfoHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 20,
  },
  modalDeviceName: {
    fontSize: 18,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  progressContainer: {
    marginBottom: 20,
  },
  progressHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  progressTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  progressStep: {
    fontSize: 14,
    color: '#8B5CF6',
    fontWeight: '500',
  },
  progressBar: {
    height: 8,
    backgroundColor: '#333333',
    borderRadius: 4,
    marginBottom: 16,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    backgroundColor: '#8B5CF6',
    borderRadius: 4,
  },
  currentStepContainer: {
    marginBottom: 12,
  },
  currentStepLabel: {
    fontSize: 14,
    color: '#A0A0A0',
    marginBottom: 4,
  },
  currentStepText: {
    fontSize: 14,
    color: '#FFFFFF',
    fontWeight: '500',
  },
  transactionStatusContainer: {
    marginBottom: 12,
  },
  transactionStatusLabel: {
    fontSize: 14,
    color: '#A0A0A0',
    marginBottom: 4,
  },
  transactionStatusText: {
    fontSize: 14,
    color: '#8B5CF6',
    fontWeight: '500',
  },
  nonceContainer: {
    marginBottom: 12,
  },
  nonceLabel: {
    fontSize: 14,
    color: '#A0A0A0',
    marginBottom: 4,
  },
  nonceText: {
    fontSize: 14,
    color: '#FFFFFF',
    fontWeight: '500',
    fontFamily: 'monospace',
  },
  modalNote: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    backgroundColor: '#1A0F2E',
    borderRadius: 8,
    padding: 12,
    borderWidth: 1,
    borderColor: '#8B5CF6',
  },
  modalNoteText: {
    flex: 1,
    fontSize: 12,
    color: '#A0A0A0',
    lineHeight: 16,
  },
  revokeSection: {
    marginBottom: 20,
  },
  revokeSectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
    marginBottom: 12,
  },
  revokeInputContainer: {
    flexDirection: 'row',
    gap: 12,
    alignItems: 'center',
  },
  revokeInput: {
    flex: 1,
    backgroundColor: '#1A1A1A',
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: '#333333',
    color: '#FFFFFF',
    fontSize: 14,
  },
  revokeButton: {
    backgroundColor: '#EF4444',
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  revokeButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
  },
  revokeButtonDisabled: {
    backgroundColor: '#666666',
    opacity: 0.6,
  },
  revokeAllButton: {
    backgroundColor: '#DC2626',
    borderRadius: 12,
    paddingVertical: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    borderWidth: 1,
    borderColor: '#EF4444',
  },
  revokeAllButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  installationDetailsButton: {
    padding: 8,
    backgroundColor: '#2A1A0A',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#F59E0B',
  },
  detailsContainer: {
    marginBottom: 20,
  },
  addressList: {
    flex: 1,
  },
  tokenLimitsList: {
    flex: 1,
  },
  tokenLimitItem: {
    marginBottom: 4,
  },
  modalActions: {
    flexDirection: 'row',
    justifyContent: 'center',
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: '#333333',
  },
  revokeFromDetailsButton: {
    backgroundColor: '#EF4444',
    borderRadius: 8,
    paddingHorizontal: 20,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  revokeFromDetailsButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  addressContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1A1A1A',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: '#333333',
    gap: 8,
    flex: 1,
  },
  addressText: {
    flex: 1,
    fontSize: 14,
    color: '#FFFFFF',
    fontFamily: 'monospace',
  },
  addressSection: {
    marginBottom: 12,
  },
  addressRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 4,
  },
  shortAddressText: {
    fontSize: 14,
    color: '#FFFFFF',
    fontFamily: 'monospace',
  },
  copyButton: {
    padding: 6,
    backgroundColor: '#1A1A1A',
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#333333',
  },
  viewFullButton: {
    padding: 6,
    backgroundColor: '#1A1A1A',
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#333333',
  },
  viewRestrictionsButton: {
    padding: 6,
    backgroundColor: '#1A1A1A',
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#333333',
  },
  dateSection: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  dateLabel: {
    fontSize: 14,
    color: '#A0A0A0',
    fontWeight: '500',
  },
  dateValue: {
    fontSize: 14,
    color: '#FFFFFF',
    fontWeight: '500',
  },
  fullAddressContainer: {
    backgroundColor: '#1A1A1A',
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: '#333333',
    marginBottom: 20,
  },
  fullAddressText: {
    fontSize: 16,
    color: '#FFFFFF',
    fontFamily: 'monospace',
    textAlign: 'center',
    lineHeight: 24,
  },
  modalCopyButton: {
    backgroundColor: '#8B5CF6',
    borderRadius: 12,
    paddingVertical: 16,
    paddingHorizontal: 24,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    shadowColor: '#8B5CF6',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
    borderWidth: 1,
    borderColor: '#A78BFA',
  },
  copyButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  ongoingInstallationCard: {
    backgroundColor: '#1A1A1A',
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#8B5CF6',
  },
  ongoingHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
    gap: 12,
  },
  ongoingTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#FFFFFF',
    flex: 1,
  },
  ongoingBadge: {
    backgroundColor: '#8B5CF6',
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  ongoingBadgeText: {
    fontSize: 10,
    fontWeight: 'bold',
    color: '#FFFFFF',
    letterSpacing: 0.5,
  },
  ongoingDetails: {
    marginBottom: 16,
  },
  ongoingDeviceName: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 4,
  },
  ongoingKeyType: {
    fontSize: 14,
    color: '#8B5CF6',
    marginBottom: 12,
  },
  ongoingProgress: {
    gap: 8,
  },
  ongoingProgressBar: {
    height: 6,
    backgroundColor: '#333333',
    borderRadius: 3,
    overflow: 'hidden',
  },
  ongoingProgressFill: {
    height: '100%',
    backgroundColor: '#8B5CF6',
    borderRadius: 3,
  },
  ongoingProgressText: {
    fontSize: 12,
    color: '#A0A0A0',
    fontWeight: '500',
  },
  viewInstallationButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: '#2A1A2A',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#8B5CF6',
  },
  viewInstallationText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#8B5CF6',
  },
  debugSection: {
    margin: 16,
    padding: 16,
    backgroundColor: '#1A1A1A',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#333333',
  },
  debugSectionTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 12,
  },
  debugButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: '#2A1A1A',
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: '#EF4444',
    marginBottom: 8,
  },
  debugButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#EF4444',
  },
  clearAllButton: {
    backgroundColor: '#EF4444',
    borderColor: '#EF4444',
  },
  clearAllButtonText: {
    color: '#FFFFFF',
  },
  
  // Restrictions Modal Styles
  restrictionsModal: {
    backgroundColor: '#1A1A1A',
    borderRadius: 16,
    margin: 20,
    maxHeight: '80%',
    width: '90%',
    alignSelf: 'center',
  },
  restrictionsModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#333333',
  },
  restrictionsHeaderButtons: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  refreshFromContractButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1A1A1A',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#8B5CF6',
    gap: 6,
  },
  refreshFromContractText: {
    color: '#8B5CF6',
    fontSize: 12,
    fontWeight: '500',
    textAlign: 'center',
  },
  refreshButtonContainer: {
    paddingHorizontal: 20,
    paddingVertical: 12,
    backgroundColor: '#1A1A1A',
    borderColor: '#333333',
    alignItems: 'center',
    marginBottom: 12
  },
  restrictionsModalTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  restrictionsContent: {
    maxHeight: 420,
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 40,
  },
  restrictionsSection: {
    marginTop: 12,
    marginBottom: 12,
  },
  restrictionsSectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
    marginBottom: 12,
  },
  restrictionsItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
    gap: 8,
  },
  restrictionsLabel: {
    fontSize: 14,
    color: '#CCCCCC',
    fontWeight: '500',
    minWidth: 120,
  },
  restrictionsValue: {
    fontSize: 14,
    color: '#FFFFFF',
    flex: 1,
  },
  restrictionsList: {
    gap: 8,
  },
  restrictionsListItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    padding: 16,
    backgroundColor: '#0F0F0F',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#333333',
    gap: 8,
  },
  restrictionsListItemText: {
    fontSize: 14,
    color: '#FFFFFF',
    flex: 1,
  },
  tokenHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  tokenStatusPill: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    fontSize: 11,
    fontWeight: '700',
    overflow: 'hidden',
    marginBottom: 4
  },
  tokenStatusEnabled: {
    color: '#0ECB81',
    backgroundColor: '#0ECB811A',
  },
  tokenStatusDisabled: {
    color: '#F87171',
    backgroundColor: '#F871711A',
  },
  restrictionsTokenMetaSmall: {
    fontSize: 11,
    color: '#888888',
    fontFamily: 'monospace',
    marginTop: 2,
  },
  tokenLimitRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
    marginTop: 12,
    flexWrap: 'wrap',
  },
  tokenLimitBox: {
    flex: 1,
    backgroundColor: '#1F1F1F',
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: '#333333',
  },
  tokenLimitLabel: {
    fontSize: 12,
    color: '#A0A0A0',
    marginBottom: 4,
    fontWeight: '600',
  },
  tokenLimitValue: {
    fontSize: 14,
    color: '#FFFFFF',
    fontWeight: '600',
  },
  tokenUsageRow: {
    marginTop: 6,
  },
  tokenUsageText: {
    fontSize: 12,
    color: '#A0A0A0',
  },
  restrictionsSelectorText: {
    fontSize: 12,
    color: '#666666',
    fontFamily: 'monospace',
  },
  restrictionsEmpty: {
    fontSize: 14,
    color: '#666666',
    fontStyle: 'italic',
    textAlign: 'center',
    padding: 20,
  },
  restrictionsWarningText: {
    fontSize: 14,
    color: '#EF4444',
    marginLeft: 8,
    flex: 1,
  },
  
  // Enhanced Permission Styles
  permissionsList: {
    gap: 16,
  },
  permissionItem: {
    backgroundColor: '#2A2A2A',
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: '#333333',
  },
  permissionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
    gap: 8,
  },
  permissionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  permissionDetails: {
    gap: 8,
  },
  permissionDetailRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 6,
  },
  permissionDetailLabel: {
    fontSize: 13,
    color: '#CCCCCC',
    fontWeight: '500',
    minWidth: 140,
    marginRight: 8,
  },
  permissionDetailValue: {
    fontSize: 13,
    color: '#FFFFFF',
    flex: 1,
    fontFamily: 'monospace',
  },
  usageNormal: {
    color: '#10B981', // Green for normal usage
  },
  usageExceeded: {
    color: '#EF4444', // Red for exceeded usage
    fontWeight: 'bold',
  },
  rulesList: {
    marginTop: 4,
    marginLeft: 8,
  },
  ruleText: {
    fontSize: 12,
    color: '#A0A0A0',
    marginBottom: 2,
  },
  
  // Summary Grid Styles
  summaryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  summaryItem: {
    backgroundColor: '#2A2A2A',
    borderRadius: 8,
    padding: 12,
    flex: 1,
    minWidth: '45%',
    alignItems: 'center',
  },
  summaryLabel: {
    fontSize: 12,
    color: '#CCCCCC',
    marginBottom: 4,
    textAlign: 'center',
  },
  summaryValue: {
    fontSize: 16,
    fontWeight: '600',
    color: '#10B981',
    textAlign: 'center',
  },
  
  // Modal Footer Styles
  restrictionsModalFooter: {
    padding: 20,
    borderTopWidth: 1,
    borderTopColor: '#333333',
    backgroundColor: '#1A1A1A',
  },
  closeModalButton: {
    backgroundColor: '#8B5CF6',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    alignItems: 'center',
  },
  closeModalButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
});
