import { StyleSheet } from 'react-native';


export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0F0F0F',
  },
  scrollView: {
    flex: 1,
  },
  content: {
    paddingHorizontal: 24,
    paddingTop: 16,
    paddingBottom: 40,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 32,
  },
  backButton: {
    padding: 8,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  placeholder: {
    width: 40,
  },
  section: {
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#FFFFFF',
    marginBottom: 8,
  },
  sectionSubtitle: {
    fontSize: 14,
    color: '#A0A0A0',
    marginBottom: 16,
  },
  input: {
    backgroundColor: '#1A1A1A',
    borderRadius: 12,
    padding: 16,
    fontSize: 16,
    color: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#333333',
  },
  connectionStatus: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    gap: 12,
  },
  connectionStatusConnected: {
    backgroundColor: '#0F1A0F',
    borderColor: '#10B981',
  },
  connectionStatusDisconnected: {
    backgroundColor: '#1A0F0F',
    borderColor: '#EF4444',
  },
  connectionStatusText: {
    flex: 1,
    fontSize: 16,
    fontWeight: '500',
  },
  connectionStatusTextConnected: {
    color: '#10B981',
  },
  connectionStatusTextDisconnected: {
    color: '#EF4444',
  },
  connectionInfo: {
    flex: 1,
  },
  connectionSubtext: {
    fontSize: 12,
    color: '#A0A0A0',
    marginTop: 2,
  },
  refreshButton: {
    padding: 8,
    backgroundColor: '#1A1A1A',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#8B5CF6',
  },
  errorContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1A0F0F',
    borderRadius: 8,
    padding: 12,
    marginTop: 12,
    borderWidth: 1,
    borderColor: '#EF4444',
    gap: 8,
  },
  errorText: {
    flex: 1,
    fontSize: 14,
    color: '#EF4444',
  },
  inputErrorText: {
    fontSize: 12,
    color: '#EF4444',
    marginTop: 4,
  },
  warningContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: '#1A0A0F',
    borderRadius: 12,
    padding: 16,
    marginTop: 16,
    borderWidth: 1,
    borderColor: '#F59E0B',
    gap: 12,
  },
  warningContent: {
    flex: 1,
  },
  warningSectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#F59E0B',
    marginBottom: 8,
  },
  warningText: {
    fontSize: 14,
    color: '#A0A0A0',
    lineHeight: 20,
    marginBottom: 12,
  },
  warningSteps: {
    fontSize: 14,
    fontWeight: '600',
    color: '#F59E0B',
    marginBottom: 8,
  },
  warningStep: {
    fontSize: 13,
    color: '#A0A0A0',
    marginBottom: 4,
    paddingLeft: 8,
  },
  inputDisabled: {
    backgroundColor: '#0F0F0F',
    borderColor: '#333333',
    opacity: 0.5,
  },
  keyTypeContainerDisabled: {
    opacity: 0.5,
  },
  keyTypeOptionDisabled: {
    backgroundColor: '#0F0F0F',
    borderColor: '#333333',
  },
  keyTypeContainer: {
    gap: 12,
  },
  keyTypeOption: {
    backgroundColor: '#1A1A1A',
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: '#333333',
    position: 'relative',
  },
  keyTypeOptionSelected: {
    borderColor: '#8B5CF6',
    backgroundColor: '#1A0A2E',
  },
  keyTypeHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 8,
  },
  keyTypeTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  keyTypeTitleSelected: {
    color: '#8B5CF6',
  },
  keyTypeDescription: {
    fontSize: 14,
    color: '#A0A0A0',
    marginBottom: 8,
  },
  recommendedBadge: {
    position: 'absolute',
    top: 12,
    right: 12,
    backgroundColor: '#10B981',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  recommendedBadgeSelected: {
    backgroundColor: '#10B981',
  },
  recommendedText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  recommendedTextSelected: {
    color: '#FFFFFF',
  },
  warningBadge: {
    position: 'absolute',
    top: 12,
    right: 12,
    backgroundColor: '#EF4444',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  warningBadgeSelected: {
    backgroundColor: '#EF4444',
  },
  // Renamed to avoid duplicate key error
  warningBadgeText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  warningTextSelected: {
    color: '#FFFFFF',
  },
  subsection: {
    marginBottom: 24,
  },
  subsectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  subsectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  requiredIndicator: {
    fontSize: 12,
    fontWeight: '500',
    color: '#EF4444',
  },
  emptyStateText: {
    fontSize: 14,
    color: '#A0A0A0',
    marginTop: 8,
  },
  whitelistToggle: {
    flexDirection: 'row',
    backgroundColor: '#1A1A1A',
    borderRadius: 8,
    padding: 4,
    marginBottom: 16,
  },
  toggleOption: {
    flex: 1,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 6,
    alignItems: 'center',
  },
  toggleOptionSelected: {
    backgroundColor: '#8B5CF6',
  },
  toggleText: {
    fontSize: 14,
    fontWeight: '500',
    color: '#A0A0A0',
  },
  toggleTextSelected: {
    color: '#FFFFFF',
  },
  whitelistContainer: {
    gap: 8,
  },
  addAddressContainer: {
    flexDirection: 'row',
    gap: 8,
  },
  addressInput: {
    flex: 1,
    backgroundColor: '#1A1A1A',
    borderRadius: 8,
    padding: 12,
    fontSize: 14,
    color: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#333333',
  },
  addButton: {
    backgroundColor: '#8B5CF6',
    borderRadius: 8,
    padding: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  addressItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1A1A1A',
    borderRadius: 8,
    padding: 12,
    borderWidth: 1,
    borderColor: '#333333',
    gap: 8,
  },
  addressText: {
    flex: 1,
    fontSize: 14,
    color: '#FFFFFF',
    fontFamily: 'monospace',
  },
  removeButton: {
    padding: 4,
  },
  selectTokenButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#1A1A1A',
    borderRadius: 8,
    padding: 12,
    borderWidth: 1,
    borderColor: '#333333',
    borderStyle: 'dashed',
    marginTop: 8,
  },
  selectTokenButtonText: {
    color: '#10B981',
    fontSize: 14,
    fontWeight: '500',
  },
  tokenLimitItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1A1A1A',
    borderRadius: 8,
    padding: 12,
    borderWidth: 1,
    borderColor: '#333333',
    marginBottom: 8,
    gap: 12,
  },
  tokenInfo: {
    flex: 1,
  },
  tokenSymbol: {
    fontSize: 14,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  tokenName: {
    fontSize: 14,
    fontWeight: '600',
    color: '#E5E7EB',
  },
  tokenNameSelected: {
    color: '#10B981',
  },
  tokenAddress: {
    fontSize: 12,
    color: '#A0A0A0',
    fontFamily: 'monospace',
  },
  tokenMeta: {
    fontSize: 12,
    color: '#A0A0A0',
  },
  tokenLimitsContainer: {
    gap: 12,
    marginTop: 12,
  },
  tokenLimitCard: {
    backgroundColor: '#1A1A1A',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#333333',
    padding: 12,
    gap: 12,
  },
  tokenLimitHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  limitRow: {
    flexDirection: 'row',
    gap: 12,
  },
  limitField: {
    flex: 1,
    gap: 6,
  },
  limitLabel: {
    color: '#9CA3AF',
    fontSize: 12,
  },
  limitInput: {
    backgroundColor: '#111827',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#1F2937',
    padding: 10,
    color: '#FFFFFF',
  },
  tokenList: {
    flex: 1,
    paddingHorizontal: 20,
    paddingVertical: 12,
    marginTop: 4,
  },
  tokenListContent: {
    gap: 12,
  },
  tokenItem: {
    borderWidth: 1,
    borderColor: '#333333',
    backgroundColor: '#1A1A1A',
    padding: 12,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  tokenItemSelected: {
    borderColor: '#10B981',
    backgroundColor: '#0F1A0F',
  },
  tokenBadge: {
    width: 10,
    height: 10,
    borderRadius: 5,
  },
  limitInfo: {
    flex: 1,
  },
  limitText: {
    fontSize: 12,
    color: '#A0A0A0',
  },
  addTokenContainer: {
    flexDirection: 'row',
    gap: 8,
    alignItems: 'center',
  },
  tokenInput: {
    flex: 1,
    backgroundColor: '#1A1A1A',
    borderRadius: 8,
    padding: 8,
    fontSize: 12,
    color: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#333333',
  },
  createButton: {
    backgroundColor: '#8B5CF6',
    borderRadius: 12,
    paddingVertical: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    marginTop: 16,
  },
  createButtonDisabled: {
    backgroundColor: '#4A4A4A',
  },
  createButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  warningModal: {
    backgroundColor: '#1A1A1A',
    borderRadius: 16,
    padding: 24,
    width: '100%',
    maxWidth: 400,
  },
  warningHeader: {
    alignItems: 'center',
    marginBottom: 20,
  },
  warningTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginTop: 12,
  },
  warningTextModal: { // Renamed from warningText to avoid duplicate key
    fontSize: 16,
    color: '#FFFFFF',
    marginBottom: 16,
    lineHeight: 22,
  },
  warningList: {
    marginBottom: 16,
  },
  warningListItem: {
    fontSize: 14,
    color: '#A0A0A0',
    marginBottom: 4,
  },
  warningRecommendation: {
    fontSize: 14,
    color: '#F59E0B',
    fontWeight: '600',
    marginBottom: 24,
    lineHeight: 20,
  },
  warningButtons: {
    flexDirection: 'row',
    gap: 12,
  },
  warningButtonSecondary: {
    flex: 1,
    backgroundColor: '#333333',
    borderRadius: 8,
    paddingVertical: 12,
    alignItems: 'center',
  },
  warningButtonSecondaryText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  warningButtonPrimary: {
    flex: 1,
    backgroundColor: '#EF4444',
    borderRadius: 8,
    paddingVertical: 12,
    alignItems: 'center',
  },
  warningButtonPrimaryText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  // Address Confirmation Modal Styles
  confirmationModal: {
    backgroundColor: '#1A1A1A',
    borderRadius: 16,
    padding: 24,
    width: '100%',
    maxWidth: 400,
  },
  confirmationHeader: {
    alignItems: 'center',
    marginBottom: 20,
  },
  confirmationTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginTop: 12,
  },
  confirmationText: {
    fontSize: 16,
    color: '#FFFFFF',
    marginBottom: 20,
    lineHeight: 22,
    textAlign: 'center',
  },
  addressContainer: {
    backgroundColor: '#0F0F0F',
    borderRadius: 12,
    padding: 16,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#333333',
  },
  addressLabel: {
    fontSize: 14,
    color: '#A0A0A0',
    marginBottom: 8,
    fontWeight: '600',
  },
  addressDisplay: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexWrap: 'wrap',
  },
  confirmationAddressText: {
    flex: 1,
    fontSize: 12,
    color: '#FFFFFF',
    fontFamily: 'monospace',
    backgroundColor: '#1A1A1A',
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#333333',
    lineHeight: 16,
  },
  copyButton: {
    padding: 12,
    backgroundColor: '#1A1A1A',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#8B5CF6',
  },
  confirmationWarning: {
    fontSize: 14,
    color: '#F59E0B',
    fontWeight: '600',
    marginBottom: 24,
    lineHeight: 20,
    textAlign: 'center',
  },
  confirmationButtons: {
    flexDirection: 'row',
    gap: 12,
  },
  confirmationButtonSecondary: {
    flex: 1,
    backgroundColor: '#333333',
    borderRadius: 8,
    paddingVertical: 12,
    alignItems: 'center',
  },
  confirmationButtonSecondaryText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  confirmationButtonPrimary: {
    flex: 1,
    backgroundColor: '#10B981',
    borderRadius: 8,
    paddingVertical: 12,
    alignItems: 'center',
  },
  confirmationButtonPrimaryText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  // Blockchain Progress Styles
  progressContainer: {
    backgroundColor: '#1A1A1A',
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: '#333333',
  },
  progressHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 16,
  },
  progressTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#8B5CF6',
  },
  progressStep: {
    marginBottom: 12,
  },
  progressStepLabel: {
    fontSize: 12,
    color: '#A0A0A0',
    fontWeight: '600',
    marginBottom: 4,
  },
  progressStepText: {
    fontSize: 14,
    color: '#FFFFFF',
    fontFamily: 'monospace',
    backgroundColor: '#0F0F0F',
    padding: 8,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#333333',
  },
  progressNote: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    backgroundColor: '#1A0A2E',
    borderRadius: 8,
    padding: 12,
    borderWidth: 1,
    borderColor: '#8B5CF6',
  },
  progressNoteText: {
    flex: 1,
    fontSize: 12,
    color: '#A0A0A0',
    lineHeight: 16,
  },
  
  // Simplified progress styles
  simpleProgressContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 20,
  },
  stepContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  stepCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    borderWidth: 2,
    borderColor: '#333333',
    backgroundColor: '#1A1A1A',
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 10,
  },
  stepCircleActive: {
    borderColor: '#007AFF',
    backgroundColor: '#001A3A',
  },
  stepCircleCompleted: {
    borderColor: '#34C759',
    backgroundColor: '#003A1A',
  },
  stepText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#666666',
    textAlign: 'center',
  },
  stepTextActive: {
    color: '#007AFF',
  },
  stepTextCompleted: {
    color: '#34C759',
    fontSize: 16,
  },
  stepArrow: {
    marginHorizontal: 5,
  },
  stepArrowText: {
    fontSize: 16,
    color: '#666666',
  },
  progressMessageContainer: {
    marginTop: 20,
    padding: 16,
    backgroundColor: '#1A1A1A',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#333333',
  },
  progressMessage: {
    fontSize: 14,
    color: '#FFFFFF',
    textAlign: 'center',
    marginBottom: 12,
  },
  progressBarContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  progressBar: {
    flex: 1,
    height: 6,
    backgroundColor: '#333333',
    borderRadius: 3,
    overflow: 'hidden',
  },
  progressBarFill: {
    height: '100%',
    backgroundColor: '#007AFF',
    borderRadius: 3,
  },
  progressPercentage: {
    fontSize: 12,
    color: '#A0A0A0',
    fontWeight: '600',
    minWidth: 35,
  },
  transactionStatusContainer: {
    marginTop: 12,
    padding: 12,
    backgroundColor: '#0F0F0F',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#333333',
  },
  transactionStatusText: {
    fontSize: 12,
    color: '#A0A0A0',
    fontFamily: 'monospace',
    textAlign: 'center',
  },
  cancelButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: '#1A0F0F',
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: '#EF4444',
    marginTop: 16,
  },
  cancelButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#EF4444',
  },
  
  // CallPolicy Styles
  advancedBadge: {
    backgroundColor: '#1A0A2E',
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderWidth: 1,
    borderColor: '#8B5CF6',
  },
  advancedBadgeSelected: {
    backgroundColor: '#8B5CF6',
  },
  advancedText: {
    fontSize: 10,
    fontWeight: '600',
    color: '#8B5CF6',
  },
  advancedTextSelected: {
    color: '#FFFFFF',
  },
  
  // Target Address Styles
  targetList: {
    marginTop: 12,
  },
  targetItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#1A1A1A',
    borderRadius: 8,
    padding: 12,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: '#333333',
  },
  targetInfo: {
    flex: 1,
  },
  targetName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
    marginBottom: 4,
  },
  targetAddress: {
    fontSize: 12,
    color: '#A0A0A0',
    fontFamily: 'monospace',
  },
  addTargetButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: '#0F1A0F',
    borderRadius: 8,
    padding: 12,
    borderWidth: 1,
    borderColor: '#10B981',
    marginTop: 12,
  },
  addTargetText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#10B981',
  },
  
  // Actions Grid Styles
  actionsGrid: {
    marginTop: 12,
  },
  actionItem: {
    backgroundColor: '#1A1A1A',
    borderRadius: 8,
    padding: 12,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: '#333333',
  },
  actionItemSelected: {
    backgroundColor: '#0F1A0F',
    borderColor: '#10B981',
  },
  actionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 4,
  },
  actionName: {
    fontSize: 14,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  actionNameSelected: {
    color: '#10B981',
  },
  actionBadge: {
    borderRadius: 4,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  transferBadge: {
    backgroundColor: '#1A0A2E',
  },
  approveBadge: {
    backgroundColor: '#1A2E0A',
  },
  swapBadge: {
    backgroundColor: '#2E1A0A',
  },
  stakeBadge: {
    backgroundColor: '#0A1A2E',
  },
  otherBadge: {
    backgroundColor: '#2E2E2E',
  },
  actionBadgeText: {
    fontSize: 10,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  actionDescription: {
    fontSize: 12,
    color: '#A0A0A0',
  },
  
  // Limits Styles
  limitsContainer: {
    marginTop: 12,
  },
  limitItem: {
    marginBottom: 16,
  },
  limitLabel: {
    fontSize: 14,
    fontWeight: '500',
    color: '#FFFFFF',
    marginBottom: 8,
  },
  limitInput: {
    backgroundColor: '#0F0F0F',
    borderRadius: 8,
    padding: 12,
    borderWidth: 1,
    borderColor: '#333333',
    fontSize: 14,
    color: '#FFFFFF',
  },
  limitInputError: {
    borderColor: '#EF4444',
  },
  
  // Summary Styles
  summaryContainer: {
    backgroundColor: '#0F1A0F',
    borderRadius: 8,
    padding: 12,
    marginTop: 16,
    borderWidth: 1,
    borderColor: '#10B981',
  },
  summaryTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#10B981',
    marginBottom: 4,
  },
  summaryText: {
    fontSize: 12,
    color: '#A0A0A0',
    lineHeight: 16,
  },
  
  // Target Modal Styles
  targetModal: {
    backgroundColor: '#1A1A1A',
    borderRadius: 16,
    margin: 20,
    maxHeight: '75%',
    borderWidth: 1,
    borderColor: '#333333',
  },
  targetModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#333333',
  },
  targetModalTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  targetModalContent: {
    padding: 20,
  },
  targetModalDescription: {
    fontSize: 14,
    color: '#A0A0A0',
    marginBottom: 20,
    lineHeight: 20,
  },
  targetModalNote: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    backgroundColor: '#1A0A2E',
    borderRadius: 8,
    padding: 12,
    marginTop: 16,
    borderWidth: 1,
    borderColor: '#8B5CF6',
  },
  targetModalNoteText: {
    flex: 1,
    fontSize: 12,
    color: '#A0A0A0',
    lineHeight: 16,
  },
  targetModalButtons: {
    flexDirection: 'row',
    gap: 12,
    padding: 20,
    borderTopWidth: 1,
    borderTopColor: '#333333',
  },
  targetButtonSecondary: {
    flex: 1,
    backgroundColor: '#1A1A1A',
    borderRadius: 8,
    padding: 12,
    borderWidth: 1,
    borderColor: '#333333',
    alignItems: 'center',
  },
  targetButtonSecondaryText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#A0A0A0',
  },
  targetButtonPrimary: {
    flex: 1,
    backgroundColor: '#10B981',
    borderRadius: 8,
    padding: 12,
    alignItems: 'center',
  },
  targetButtonPrimaryText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  
  // Missing styles
  subsectionDescription: {
    fontSize: 12,
    color: '#A0A0A0',
    marginBottom: 12,
    lineHeight: 16,
  },
  closeButton: {
    padding: 4,
  },
  inputGroup: {
    marginBottom: 20,
  },
  inputLabel: {
    fontSize: 14,
    fontWeight: '500',
    color: '#FFFFFF',
    marginBottom: 8,
  },
  textInput: {
    backgroundColor: '#0F0F0F',
    borderRadius: 8,
    padding: 12,
    borderWidth: 1,
    borderColor: '#333333',
    fontSize: 14,
    color: '#FFFFFF',
  },
  
  // Selected Actions Styles
  selectedActionsContainer: {
    marginBottom: 12,
  },
  selectedActionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#1A1A1A',
    borderRadius: 8,
    padding: 12,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: '#333333',
  },
  
  // Transfer Card Styles
  transferCard: {
    backgroundColor: '#1A1A1A',
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#333333',
  },
  transferCardEnabled: {
    borderColor: '#10B981',
    backgroundColor: '#0F1A0F',
  },
  transferCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  transferCardInfo: {
    flex: 1,
  },
  transferCardTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#666666',
    marginBottom: 4,
  },
  transferCardTitleEnabled: {
    color: '#FFFFFF',
  },
  transferCardDescription: {
    fontSize: 12,
    color: '#CCCCCC',
    marginBottom: 8,
  },
  transferStatusContainer: {
    flexDirection: 'row',
    gap: 8,
  },
  transferStatusItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  transferStatusText: {
    fontSize: 12,
    color: '#10B981',
    fontWeight: '500',
  },
  transferCardControls: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  transferToggle: {
    width: 44,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#333333',
    padding: 2,
    justifyContent: 'center',
  },
  transferToggleEnabled: {
    backgroundColor: '#10B981',
  },
  transferToggleThumb: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#FFFFFF',
    alignSelf: 'flex-start',
  },
  transferToggleThumbEnabled: {
    alignSelf: 'flex-end',
  },
  transferSettingsButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#0F0F0F',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#10B981',
  },
  selectedActionInfo: {
    flex: 1,
  },
  selectedActionName: {
    fontSize: 14,
    fontWeight: '600',
    color: '#FFFFFF',
    marginBottom: 2,
  },
  selectedActionDescription: {
    fontSize: 12,
    color: '#A0A0A0',
  },
  removeActionButton: {
    padding: 4,
  },
  addActionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#1A1A1A',
    borderRadius: 8,
    padding: 12,
    borderWidth: 1,
    borderColor: '#333333',
    borderStyle: 'dashed',
  },
  addActionText: {
    fontSize: 14,
    fontWeight: '500',
    color: '#10B981',
    marginLeft: 8,
  },
  
  // Action Selector Modal Styles
  actionModal: {
    backgroundColor: '#1A1A1A',
    borderRadius: 16,
    margin: 40,
    maxHeight: '70%',
    minHeight: '50%',
    width: '90%',
    alignSelf: 'center',
  },
  actionModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#333333',
  },
  actionModalTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#0F0F0F',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    margin: 20,
    marginTop: 20,
    borderWidth: 1,
    borderColor: '#333333',
  },
  searchInput: {
    flex: 1,
    fontSize: 14,
    color: '#FFFFFF',
    marginLeft: 8,
  },
  actionList: {
    flex: 1,
    paddingHorizontal: 20,
    paddingBottom: 40,
  },
  actionListItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#0F0F0F',
    borderRadius: 8,
    padding: 12,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: '#333333',
  },
  actionListItemSelected: {
    backgroundColor: '#1A2E0A',
    borderColor: '#10B981',
  },
  actionListItemContent: {
    flex: 1,
  },
  actionListItemHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  actionListItemName: {
    fontSize: 14,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  actionListItemNameSelected: {
    color: '#10B981',
  },
  actionListItemBadge: {
    borderRadius: 4,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  actionListItemBadgeText: {
    fontSize: 10,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  actionListItemDescription: {
    fontSize: 12,
    color: '#A0A0A0',
    marginBottom: 2,
  },
  actionListItemSelector: {
    fontSize: 10,
    color: '#666666',
    fontFamily: 'monospace',
  },

  // Token Selector Modal Styles
  tokenModal: {
    backgroundColor: '#1A1A1A',
    borderRadius: 16,
    margin: 20,
    maxHeight: '75%',
    alignSelf: 'center',
    borderWidth: 1,
    borderColor: '#333333',
  },
  tokenModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#333333',
  },
  tokenModalTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  tokenModalFooter: {
    padding: 20,
    borderTopWidth: 1,
    borderTopColor: '#333333',
  },
  tokenModalButton: {
    backgroundColor: '#10B981',
    borderRadius: 8,
    padding: 12,
    alignItems: 'center',
  },
  tokenModalButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  
  // Transfer Options Modal Styles
  transferModal: {
    backgroundColor: '#1A1A1A',
    borderRadius: 16,
    margin: 40,
    maxHeight: '60%',
    width: '90%',
    alignSelf: 'center',
  },
  transferModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#333333',
  },
  transferModalTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  transferOptionsContainer: {
    padding: 20,
  },
  transferOptionsDescription: {
    fontSize: 14,
    color: '#CCCCCC',
    marginBottom: 20,
    lineHeight: 20,
  },
  transferOption: {
    backgroundColor: '#0F0F0F',
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#333333',
  },
  transferOptionSelected: {
    borderColor: '#10B981',
    backgroundColor: '#0F1A0F',
  },
  transferOptionContent: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  transferOptionText: {
    flex: 1,
    marginLeft: 12,
  },
  transferOptionTitle: {
    fontSize: 16,
    fontWeight: '500',
    color: '#FFFFFF',
    marginBottom: 4,
  },
  transferOptionTitleSelected: {
    color: '#10B981',
  },
  transferOptionDescription: {
    fontSize: 12,
    color: '#CCCCCC',
  },
  checkbox: {
    width: 24,
    height: 24,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: '#333333',
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkboxSelected: {
    backgroundColor: '#10B981',
    borderColor: '#10B981',
  },
  transferModalFooter: {
    flexDirection: 'row',
    padding: 20,
    borderTopWidth: 1,
    borderTopColor: '#333333',
    gap: 12,
  },
  transferCancelButton: {
    flex: 1,
    backgroundColor: '#333333',
    borderRadius: 8,
    padding: 12,
    alignItems: 'center',
  },
  transferCancelButtonText: {
    fontSize: 16,
    fontWeight: '500',
    color: '#FFFFFF',
  },
  transferConfirmButton: {
    flex: 1,
    backgroundColor: '#10B981',
    borderRadius: 8,
    padding: 12,
    alignItems: 'center',
  },
  transferConfirmButtonDisabled: {
    backgroundColor: '#333333',
  },
  transferConfirmButtonText: {
    fontSize: 16,
    fontWeight: '500',
    color: '#FFFFFF',
  },
  transferConfirmButtonTextDisabled: {
    color: '#666666',
  },
});